version: '3.9'

services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    image: service1:${TAG1:-latest}
    container_name: service1
    ports:
      - "8000:8000"
  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    image: service2:${TAG2:-latest}
    container_name: service2
    ports:
      - "8001:8001"
    depends_on:
      - service1
