version: '3.9'

services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    ports:
      - "8000:8000"
  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - service1
