apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: dom776
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: dom776/service1:v1.0
        ports:
        - containerPort: 8000
