pipeline {
    agent any
    stages{
        stage ("Build-images"){
            steps{
                sh "echo 'Building docker images'"
                sh "docker-compose build"              
                
            }
        }

        stage ("Integration-test"){
            steps{
                sh "echo 'Integration test stage'"                
                
            }
        }

        stage ("Unit-test"){
            steps{
                sh "echo 'Unit-test stage'"                             
                
            }
        }

        stage ("Tag-images"){
            steps{    
                sh "echo 'Taging docker iamges'"
                sh "docker tag service1:latest dom776/service1:v1.0-${BUILD_NUMBER}"
                sh "docker tag service2:latest dom776/service2:v1.0-${BUILD_NUMBER}"        
            }
        }

        stage ("Publish-images"){
            steps{
                withCredentials([usernamePassword(credentialsId: '38b31444-6d8b-4a06-82df-84307bccab51', usernameVariable: 'dom776', passwordVariable: 'dockerHubPswd')]) {
                    sh "docker login -u dom776 -p ${dockerHubPswd}"
                    sh "echo 'Publishing docker images'"
                    sh "docker push dom776/service1:v1.0-${BUILD_NUMBER}"
                    sh "docker push dom776/service2:v1.0-${BUILD_NUMBER}"
                }
            }
        }
    }
}


