pipeline {
    agent any
    stages{
        stage ("Build-images"){
            steps{
                sh "echo 'Building docker images'"
                sh "docker-compose build"              
                
            }
        }

        stage ("Integration-test"){
            steps{
                sh "echo 'Integration test stage'"                
                
            }
        }

        stage ("Unit-test"){
            steps{
                sh "echo 'Unit-test stage'"                             
                
            }
        }

        stage ("Tag-images"){
            steps{    
                withCredentials([string(credentialsId: 'dom776', variable: 'dockerHubPswd')]) {
                    sh "docker login -u dom776 -p ${dockerHubPswd}"
                    sh "docker push ezmamig/avl_backend:v1.0"
                    sh "docker push ezmamig/avl_client:v1.0"
                }                
            }
        }

        stage ("Publish-images"){
            steps{
                sh "echo 'Publishing docker images'"
                sh "docker push dom776/service1:v1.0"
                sh "docker push dom776/service2:v1.0"
                
            }
        }
    }
}
